name: barcodes_example
description: "A Barcodes widget example project."
version: 1.0.0+1

environment:
  sdk: ^3.7.0

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_barcodes: 
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
