name: core_example
description: This project demonstrates on how to change the appearance of Syncfusion Flutter Widgets using theme.
version: 1.0.0+1

environment:
  sdk: ^3.7.0

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_core: ^30.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

